"""added grade_level column

Revision ID: 44280a692a75
Revises: 188cca7c3da9
Create Date: 2025-09-25 00:23:42.755609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44280a692a75'
down_revision: Union[str, Sequence[str], None] = '188cca7c3da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_progress', 'p_know',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.2'::double precision"))
    op.alter_column('knowledge_progress', 'transit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.15'::double precision"))
    op.alter_column('knowledge_progress', 'slip',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.1'::double precision"))
    op.alter_column('knowledge_progress', 'guess',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.2'::double precision"))
    op.add_column('users', sa.Column('grade_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'grade_level')
    op.alter_column('knowledge_progress', 'guess',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.2'::double precision"))
    op.alter_column('knowledge_progress', 'slip',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.1'::double precision"))
    op.alter_column('knowledge_progress', 'transit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.15'::double precision"))
    op.alter_column('knowledge_progress', 'p_know',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.2'::double precision"))
    # ### end Alembic commands ###
