"""add adventures table

Revision ID: 677e14cde16a
Revises: 44280a692a75
Create Date: 2025-09-27 18:49:19.497158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677e14cde16a'
down_revision: Union[str, Sequence[str], None] = '44280a692a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adventure_id', sa.String(), nullable=False),
    sa.Column('items_collected', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cleared_ndoes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('current_adaptive_kc', sa.String(), nullable=True),
    sa.Column('enemy_level', sa.Integer(), nullable=True),
    sa.Column('enemy_writing_level', sa.Integer(), nullable=True),
    sa.Column('enemy_defense_level', sa.Integer(), nullable=True),
    sa.Column('player_level', sa.Integer(), nullable=True),
    sa.Column('writing_level', sa.Integer(), nullable=True),
    sa.Column('defense_level', sa.Integer(), nullable=True),
    sa.Column('current_floor', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adventure_id')
    )
    op.create_index(op.f('ix_adventure_id'), 'adventure', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adventure_id'), table_name='adventure')
    op.drop_table('adventure')
    # ### end Alembic commands ###
