"""cleared ndoes typo fix

Revision ID: 7a556699b955
Revises: c7a512a292e6
Create Date: 2025-10-01 21:20:06.774117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a556699b955'
down_revision: Union[str, Sequence[str], None] = 'c7a512a292e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adventure', sa.Column('cleared_nodes', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('adventure', 'cleared_ndoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adventure', sa.Column('cleared_ndoes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('adventure', 'cleared_nodes')
    # ### end Alembic commands ###
