"""changed 'user' node_structure_seed to string from JSON & added 'inventory_items' table

Revision ID: a47866424cb3
Revises: f9409a73c62a
Create Date: 2025-09-13 21:53:42.098863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a47866424cb3'
down_revision: Union[str, Sequence[str], None] = 'f9409a73c62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('cleared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_progress_level_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_user_id'), table_name='progress')
    op.drop_constraint(op.f('progress_user_id_fkey'), 'progress', type_='foreignkey')
    op.create_foreign_key(None, 'progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('progress', 'updated_at')
    op.drop_column('progress', 'status')
    op.alter_column('submissions', 'kc_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="kc_id::integer")
    op.add_column('users', sa.Column('node_structure_seed', sa.String(), nullable=True))
    op.drop_column('users', 'node_structure_seeds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('node_structure_seeds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('users', 'node_structure_seed')
    op.alter_column('submissions', 'kc_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('progress', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('progress', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.create_foreign_key(op.f('progress_user_id_fkey'), 'progress', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_progress_user_id'), 'progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_progress_level_id'), 'progress', ['level_id'], unique=False)
    op.drop_column('progress', 'cleared_at')
    # ### end Alembic commands ###
