"""add BKT params to knowledge_progress

Revision ID: f5421b632b9a
Revises: e066a12f6e59
Create Date: 2025-09-15 20:12:29.214288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5421b632b9a'
down_revision: Union[str, Sequence[str], None] = 'e066a12f6e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_progress', sa.Column('p_know', sa.Float(), nullable=True))
    op.add_column('knowledge_progress', sa.Column('transit', sa.Float(), nullable=True))
    op.add_column('knowledge_progress', sa.Column('slip', sa.Float(), nullable=True))
    op.add_column('knowledge_progress', sa.Column('guess', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_progress', 'guess')
    op.drop_column('knowledge_progress', 'slip')
    op.drop_column('knowledge_progress', 'transit')
    op.drop_column('knowledge_progress', 'p_know')
    # ### end Alembic commands ###
